export type Patient = {
  id: number;
  patient_id: string;
  username: string;
  first_name: string;
  middle_name?: string;
  last_name: string;
  suffix?: string;
  sex: string;
  email: string;
  address: string;
  contact_number: string;
  civil_status: string;
  blood_type?: string;
  birthdate: string;
  emergency_contact_name?: string;
  emergency_contact?: string;
  image_url?: string;
  created_at: string;
  updated_at: string;
};
