import type { PatientInfo, DoctorInfo, Medication } from "./types";

export const SAMPLE_PATIENTS: PatientInfo[] = [
  {
    id: "pat-1",
    patientId: "01-0001-0001-02",
    name: "Juan Dela Cruz",
    age: "21 years old",
    sex: "Male",
    birthdate: "Mar 12, 2005",
    contactNumber: "0912-345-6788",
    address: "123 Mabini St., Ermita, Manila",
    isSeniorCitizen: true,
    isPwd: true,
    avatarInitials: "JD",
  },
  {
    id: "pat-2",
    patientId: "01-0002-0004-15",
    name: "Maria Clara Santos",
    age: "34 years old",
    sex: "Female",
    birthdate: "Aug 24, 1992",
    contactNumber: "0917-889-1234",
    address: "45 Rizal Ave., Sampaloc, Manila",
    isSeniorCitizen: false,
    isPwd: false,
    avatarInitials: "MS",
  },
  {
    id: "pat-3",
    patientId: "01-0003-0012-08",
    name: "Roberto Garcia",
    age: "67 years old",
    sex: "Male",
    birthdate: "Jan 15, 1959",
    contactNumber: "0922-333-7788",
    address: "88 Luna St., Paco, Manila",
    isSeniorCitizen: true,
    isPwd: false,
    avatarInitials: "RG",
  },
];

export const DEFAULT_DOCTOR: DoctorInfo = {
  name: "Dr. LeBron R. James",
  title: "General Physician",
  licenseNumber: "123456",
  department: "Internal Medicine",
  ptrNumber: "PTR-2026-987654",
  s2Number: "S2-456789-MD",
};

export const COMMON_MEDICATIONS: Array<Omit<Medication, "id">> = [
  {
    name: "Paracetamol 500 mg",
    dosage: "500 mg",
    frequency: "3x a day",
    duration: "5 days",
    route: "Oral",
    instructions: "After meals, as needed for fever or pain",
  },
  {
    name: "Amoxicillin 500 mg",
    dosage: "500 mg",
    frequency: "3x a day",
    duration: "7 days",
    route: "Oral",
    instructions: "After meals. Complete full 7-day course.",
  },
  {
    name: "Mefenamic Acid 500 mg",
    dosage: "500 mg",
    frequency: "3x a day",
    duration: "3 days",
    route: "Oral",
    instructions: "Take with food for pain relief as needed",
  },
  {
    name: "Cetirizine 10 mg",
    dosage: "10 mg",
    frequency: "Once daily",
    duration: "7 days",
    route: "Oral",
    instructions: "Take once daily before bedtime",
  },
  {
    name: "Metformin 500 mg",
    dosage: "500 mg",
    frequency: "Twice daily",
    duration: "30 days",
    route: "Oral",
    instructions: "Take with morning and evening meals",
  },
  {
    name: "Losartan 50 mg",
    dosage: "50 mg",
    frequency: "Once daily",
    duration: "30 days",
    route: "Oral",
    instructions: "Take in the morning with or without food",
  },
  {
    name: "Omeprazole 20 mg",
    dosage: "20 mg",
    frequency: "Once daily",
    duration: "14 days",
    route: "Oral",
    instructions: "Take 30 minutes before breakfast",
  },
  {
    name: "Azithromycin 500 mg",
    dosage: "500 mg",
    frequency: "Once daily",
    duration: "3 days",
    route: "Oral",
    instructions: "Take 1 hour before or 2 hours after meals",
  },
  {
    name: "Ibuprofen 400 mg",
    dosage: "400 mg",
    frequency: "3x a day",
    duration: "5 days",
    route: "Oral",
    instructions: "Take with meals or milk",
  },
  {
    name: "Salbutamol 2 mg/5 mL",
    dosage: "5 mL",
    frequency: "3x a day",
    duration: "7 days",
    route: "Oral",
    instructions: "Take as needed for cough or wheezing",
  },
];

export const CLINIC_INFO = {
  name: "Reyna G Diagnostic Medical Clinic",
  address: "123 Health St., Manila, Philippines",
  phone: "Tel: (02) 8123 4567",
  email: "Email: info@reynag.com",
  logoUrl: "/assets/reyna-g-logo.png",
};
